# ns2d/plot_ns2d.py
#!/usr/bin/env python3
"""
Quick visualization utility for the 2D Navier–Stokes snapshot-map Hugging Face dataset
generated by "Response B" (DatasetDict saved via save_to_disk).

Examples
--------
# Save 10 examples (default) into Data/ns2d/data_plots
python Data/ns2d/plot_ns2d.py --split train

# Show one example (train split, index 0)
python Data/ns2d/plot_ns2d.py --split train --index 0 --show

# Show omega0, omegaT, and omegaT-omega0, and also plot velocity magnitude if stored
python -m ns2d.plot_ns2d --dataset_path ./data/ns2d_snapshot --split test --index 3 \
  --show_diff --velocity speed

# Save a single figure to a specific path
python Data/ns2d/plot_ns2d.py --split train --index 10 \
  --show_diff --save ./check.png
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np

try:
    import matplotlib.pyplot as plt
except ImportError as e:  # pragma: no cover
    raise ImportError("matplotlib is required for plotting. Install with: pip install matplotlib") from e

try:
    import datasets
except ImportError as e:  # pragma: no cover
    raise ImportError("datasets is required. Install with: pip install datasets") from e


DEFAULT_DATASET_PATH = Path(__file__).resolve().parent / "ns2d_snapshot"
DEFAULT_SAVE_DIR = Path(__file__).resolve().parent / "data_plots"


def _load_metadata(dataset_path: Path) -> Optional[Dict[str, Any]]:
    meta_path = dataset_path / "metadata.json"
    if not meta_path.exists():
        return None
    try:
        return json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _infer_L_from_metadata(meta: Optional[Dict[str, Any]]) -> Optional[float]:
    if not meta:
        return None
    # Response B writes meta["grid"]["L"]
    try:
        L = meta.get("grid", {}).get("L", None)
        return float(L) if L is not None else None
    except Exception:
        return None


def _infer_transpose_default(meta: Optional[Dict[str, Any]]) -> bool:
    """
    Response B states: omega[i,j] corresponds to x=i*(L/N), y=j*(L/N) (ij indexing).
    imshow expects array[row=y, col=x], so to plot x horizontally and y vertically,
    we transpose by default when we detect ij-indexing.
    """
    if not meta:
        return True  # safer default: show x on horizontal axis
    txt = ""
    try:
        ao = meta.get("axis_ordering", {}).get("omega", "")
        txt = str(ao).lower()
    except Exception:
        txt = ""
    return ("ij" in txt) or ("x = i" in txt and "y = j" in txt)


def _set_numpy_format(ds: datasets.Dataset) -> datasets.Dataset:
    # Ensures Array2D/Array3D are returned as numpy arrays.
    return ds.with_format("numpy")


def _get_dataset_split(dataset_path: Path, split: str) -> datasets.Dataset:
    obj = datasets.load_from_disk(str(dataset_path))
    if isinstance(obj, datasets.DatasetDict):
        if split not in obj:
            raise ValueError(f"Split '{split}' not found. Available splits: {list(obj.keys())}")
        return obj[split]
    # If a single Dataset was saved (unexpected), just use it.
    return obj


def _maybe_transpose(field: np.ndarray, transpose: bool) -> np.ndarray:
    if not transpose:
        return field
    if field.ndim == 2:
        return field.T
    if field.ndim == 3 and field.shape[0] == 2:  # uT: (2,N,N)
        return np.stack([field[0].T, field[1].T], axis=0)
    return field


def _compute_energy_enstrophy(omega: np.ndarray, L: float) -> Tuple[float, float]:
    """
    Kinetic energy and enstrophy from vorticity on a periodic domain.
    Uses streamfunction Poisson solve in Fourier space.
    """
    omega = np.asarray(omega, dtype=np.float64)
    N = omega.shape[0]
    if omega.shape != (N, N):
        raise ValueError("omega must be (N,N)")

    # rfft2 layout
    omega_hat = np.fft.rfft2(omega, axes=(0, 1))

    fx = np.fft.fftfreq(N, d=L / N)  # cycles per unit length
    fy = np.fft.rfftfreq(N, d=L / N)
    kx = (2.0 * np.pi * fx)[:, None]          # (N,1)
    ky = (2.0 * np.pi * fy)[None, :]          # (1,N//2+1)
    k2 = kx * kx + ky * ky

    psi_hat = np.zeros_like(omega_hat)
    nz = k2 > 0.0
    psi_hat[nz] = -omega_hat[nz] / k2[nz]
    psi_hat[0, 0] = 0.0 + 0.0j

    u_hat = 1j * ky * psi_hat
    v_hat = -1j * kx * psi_hat
    u = np.fft.irfft2(u_hat, s=(N, N), axes=(0, 1))
    v = np.fft.irfft2(v_hat, s=(N, N), axes=(0, 1))

    energy = 0.5 * float(np.mean(u * u + v * v))
    enstrophy = 0.5 * float(np.mean(omega * omega))
    return energy, enstrophy


def _stats(arr: np.ndarray) -> Dict[str, float]:
    arr = np.asarray(arr)
    return {
        "min": float(np.min(arr)),
        "max": float(np.max(arr)),
        "mean": float(np.mean(arr)),
        "std": float(np.std(arr)),
        "rms": float(np.sqrt(np.mean(arr * arr))),
    }


def _plot_field(ax, field: np.ndarray, title: str, extent: Optional[Tuple[float, float, float, float]] = None,
                vmin: Optional[float] = None, vmax: Optional[float] = None):
    im = ax.imshow(field, origin="lower", extent=extent, vmin=vmin, vmax=vmax)
    ax.set_title(title)
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)


def _save_figure(fig: plt.Figure, out_path: Path, dpi: int) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def _build_figure(
    *,
    ex: Dict[str, Any],
    split: str,
    index: int,
    L: float,
    transpose: bool,
    show_diff: bool,
    velocity: str,
    same_scale: bool,
    fig_w: Optional[float],
    fig_h: float,
    print_stats: bool,
) -> plt.Figure:
    if "omega0" not in ex or "omegaT" not in ex:
        raise KeyError("Dataset example must contain 'omega0' and 'omegaT' fields.")

    omega0 = np.asarray(ex["omega0"])
    omegaT = np.asarray(ex["omegaT"])

    omega0_plot = _maybe_transpose(omega0, transpose)
    omegaT_plot = _maybe_transpose(omegaT, transpose)

    extent = (0.0, float(L), 0.0, float(L))

    # Optional color scaling
    vmin_om = vmax_om = None
    if same_scale:
        vmin_om = float(min(np.min(omega0_plot), np.min(omegaT_plot)))
        vmax_om = float(max(np.max(omega0_plot), np.max(omegaT_plot)))

    panels = [("omega0 (t=0)", omega0_plot, vmin_om, vmax_om), ("omegaT (t=T)", omegaT_plot, vmin_om, vmax_om)]

    if show_diff:
        diff = omegaT - omega0
        diff_plot = _maybe_transpose(diff, transpose)
        panels.append(("omegaT - omega0", diff_plot, None, None))

    # Velocity panels (if present)
    if velocity != "none":
        if "uT" not in ex:
            print("Warning: --velocity requested but 'uT' field is not present in the dataset example.")
        else:
            uT = np.asarray(ex["uT"])
            uT_plot = _maybe_transpose(uT, transpose)
            u = uT_plot[0]
            v = uT_plot[1]
            if velocity == "uv":
                panels.append(("u(x,y,T)", u, None, None))
                panels.append(("v(x,y,T)", v, None, None))
            elif velocity == "speed":
                speed = np.sqrt(u * u + v * v)
                panels.append(("|u|(x,y,T)", speed, None, None))

    # Stats
    if print_stats:
        s0 = _stats(omega0)
        sT = _stats(omegaT)
        print(f"[{split}][{index}] omega0 stats: {s0}")
        print(f"[{split}][{index}] omegaT stats: {sT}")
        try:
            E0, Z0 = _compute_energy_enstrophy(omega0, L=L)
            ET, ZT = _compute_energy_enstrophy(omegaT, L=L)
            print(f"[{split}][{index}] energy:   E0={E0:.6e}, ET={ET:.6e}")
            print(f"[{split}][{index}] enstrophy Z0={Z0:.6e}, ZT={ZT:.6e}")
        except Exception as e:
            print(f"Could not compute energy/enstrophy: {e}")

    ncols = len(panels)
    fig_w = fig_w if fig_w is not None else max(4.0, 3.6 * ncols)
    fig, axes = plt.subplots(1, ncols, figsize=(fig_w, fig_h), squeeze=False)
    axes = axes[0]

    for ax, (title, field, vmin, vmax) in zip(axes, panels):
        _plot_field(ax, field, title, extent=extent, vmin=vmin, vmax=vmax)

    fig.suptitle(f"NS2D snapshot-map sample: split={split}, index={index}", y=1.02)
    fig.tight_layout()
    return fig


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot samples from the ns2d_snapshot HF dataset (Response B).")
    p.add_argument(
        "--dataset_path",
        type=str,
        default=str(DEFAULT_DATASET_PATH),
        help="Path to saved HF DatasetDict (save_to_disk folder).",
    )
    p.add_argument("--split", type=str, default="train", choices=["train", "test"], help="Dataset split.")
    p.add_argument("--index", type=int, default=0, help="Example index within the split (or start index for batch).")
    p.add_argument("--num_samples", type=int, default=10, help="Number of samples to save when batching.")
    p.add_argument("--show_diff", action="store_true", help="Also plot omegaT - omega0.")
    p.add_argument(
        "--velocity",
        type=str,
        default="none",
        choices=["none", "uv", "speed"],
        help="If uT is present, plot u/v components or speed magnitude.",
    )
    p.add_argument(
        "--same_scale",
        action="store_true",
        help="Use the same color scale for omega0 and omegaT (helps visual comparison).",
    )
    p.add_argument(
        "--transpose",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Transpose fields for imshow so x is horizontal and y is vertical. "
             "If not set, tries to infer from metadata (default: transpose for ij-indexed data).",
    )
    p.add_argument("--L", type=float, default=None, help="Domain size for axis extent. Defaults to metadata or 1.0.")
    p.add_argument("--print_stats", action="store_true", help="Print basic stats and energy/enstrophy (if L known).")
    p.add_argument(
        "--save",
        type=str,
        default=None,
        help="If set, save a single figure to this path instead of showing or batching.",
    )
    p.add_argument(
        "--save_dir",
        type=str,
        default=str(DEFAULT_SAVE_DIR),
        help="Directory for batch-saved figures (default: Data/ns2d/data_plots).",
    )
    p.add_argument("--show", action="store_true", help="Show a single figure interactively instead of saving.")
    p.add_argument("--dpi", type=int, default=150, help="DPI for saved figure.")
    p.add_argument("--fig_w", type=float, default=None, help="Figure width in inches (auto if None).")
    p.add_argument("--fig_h", type=float, default=4.0, help="Figure height in inches.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    dataset_path = Path(args.dataset_path)

    meta = _load_metadata(dataset_path)
    L_meta = _infer_L_from_metadata(meta)
    L = args.L if args.L is not None else (L_meta if L_meta is not None else 1.0)

    transpose_default = _infer_transpose_default(meta)
    transpose = transpose_default if args.transpose is None else bool(args.transpose)

    ds = _get_dataset_split(dataset_path, args.split)
    ds = _set_numpy_format(ds)

    if args.num_samples < 1:
        raise ValueError("--num_samples must be >= 1")

    if args.show and args.save is not None:
        raise ValueError("--show and --save cannot be used together.")

    if args.index < 0 or args.index >= len(ds):
        raise IndexError(f"index={args.index} out of range for split '{args.split}' (len={len(ds)})")

    if args.show:
        ex = ds[args.index]
        fig = _build_figure(
            ex=ex,
            split=args.split,
            index=args.index,
            L=L,
            transpose=transpose,
            show_diff=args.show_diff,
            velocity=args.velocity,
            same_scale=args.same_scale,
            fig_w=args.fig_w,
            fig_h=args.fig_h,
            print_stats=args.print_stats,
        )
        plt.show()
        return

    if args.save is not None:
        ex = ds[args.index]
        fig = _build_figure(
            ex=ex,
            split=args.split,
            index=args.index,
            L=L,
            transpose=transpose,
            show_diff=args.show_diff,
            velocity=args.velocity,
            same_scale=args.same_scale,
            fig_w=args.fig_w,
            fig_h=args.fig_h,
            print_stats=args.print_stats,
        )
        out = Path(args.save)
        if out.suffix == "":
            out.mkdir(parents=True, exist_ok=True)
            out = out / f"ns2d_{args.split}_idx{args.index:05d}.png"
        _save_figure(fig, out, args.dpi)
        print(f"Saved figure to: {out}")
        return

    # Batch save to directory (default behavior)
    n_available = len(ds) - args.index
    n_to_save = min(int(args.num_samples), n_available)
    if n_to_save < args.num_samples:
        print(
            f"Requested {args.num_samples} samples from index {args.index}, "
            f"but only {n_available} available. Saving {n_to_save}."
        )
    out_dir = Path(args.save_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Saving {n_to_save} samples to: {out_dir}")

    for idx in range(args.index, args.index + n_to_save):
        ex = ds[idx]
        fig = _build_figure(
            ex=ex,
            split=args.split,
            index=idx,
            L=L,
            transpose=transpose,
            show_diff=args.show_diff,
            velocity=args.velocity,
            same_scale=args.same_scale,
            fig_w=args.fig_w,
            fig_h=args.fig_h,
            print_stats=args.print_stats,
        )
        out_path = out_dir / f"ns2d_{args.split}_idx{idx:05d}.png"
        _save_figure(fig, out_path, args.dpi)
        print(f"Saved figure to: {out_path}")


if __name__ == "__main__":
    main()
